### ISSUE TITLE
Contification using Dominators (ICFP '01)

### ISSUE THREAD

**Issue by kavon** [uchicago-cs/plrg#20]
This might be a nice background/followup paper to dive into after Compiling without Continuations. I'll lead this paper whenever we schedule it.

http://dl.acm.org/citation.cfm?id=507639

**Comment by kavon** [comment]
Non-paywall Link: https://www.cs.purdue.edu/homes/suresh/502-Fall2008/papers/contification.pdf

**Comment by brianhempel** [comment]
Discussed 2018-4-17
