### ISSUE TITLE
Retrofitting Linear Types

### ISSUE THREAD

**Issue by uchwings** [uchicago-cs/plrg#27]
Linear and affine type systems have a long and storied history, but not a clear path forward to integrate with existing languages such as Ocaml or Haskell. In this paper, we introduce and study a linear type system designed with two crucial properties in mind: backwards-compatibility and code reuse across linear and non-linear users of a library. Only then can the benefits of linear types permeate conventional functional programming. Rather than bifurcate data types into linear and non-linear counterparts, we instead attach linearity to /binders/. Linear function types can receive inputs from linearly-bound values, but can also operate over unrestricted, regular values.
Linear types are an enabling tool for safe and resource efficient systems programming. We explore the power of linear types with a case study of a large, in-memory data structures that must serve responses with low latency.

https://github.com/tweag/linear-types/releases/download/v1.0/hlt.pdf

**Comment by brianhempel** [comment]
Scheduled for 2017-03-17. https://uchicago-cs.github.io/plrg/
