### ISSUE TITLE
Can functional programming be liberated from the von Neumann paradigm? (2010)

### ISSUE THREAD

**Issue by brianhempel** [uchicago-cs/plrg#56]
Conal Elliot, blog post
http://conal.net/blog/posts/can-functional-programming-be-liberated-from-the-von-neumann-paradigm

> I look at monadic IO not as any solution to functional I/O, but rather as a (clever) way not to bring I/O into the functional world. There’s a ton of confusion buzzing around monadic IO, so let me try to restate more carefully: “monadic IO” is a way to generate imperative computations (not just I/O) without having to say anything at all about the semantic content of those computations. Rather than retooling our mental habits completely away from the imperative model of computation, monadic IO is a way to hang onto these old mental habits, and use them in a hybrid functional/imperative programming style, in which the imperative doesn’t contaminate the functional, semantically.

**Comment by kavon** [comment]
Paper #57 would make a good pairing IMO.

**Comment by k4rtik** [comment]
Scheduled.
