### ISSUE TITLE
egg: Easy, Efficient, and Extensible E-graphs

### ISSUE THREAD

**Issue by wraith1995** [uchicago-cs/plrg#61]
Found at: https://arxiv.org/abs/2004.03082

I'd be willing to present this not this Wednesday, but the week after.

@brianhempel

**Comment by k4rtik** [comment]
Looks very interesting. We should certainly schedule it.

**Comment by wraith1995** [comment]
Yeah. I'd say for 5-27 unless someone wants to something else then.

**Comment by brianhempel** [comment]
Scheduled for 2020-5-27. @wraith1995 you're on to lead! We'll need some patience with the background, we're not math people.
